### ISSUE TITLE
file/popen was deprecated

### ISSUE THREAD

**Issue by tionis** [ahungry/ahungry-janet#1]
file/popen was deprecated, but is currently used in following files:
- src/janet-pq/project.janet:30
- src/webview/project.janet:11
- project.janet;234
- amalg/janet.c:12273
- amalg/janet.c:12489
- amalg/janet.c:12961

**Comment by ahungry** [comment]
Thanks, this is a good reminder when I update to work with the next version of janet - as you may have noticed, the contents of amalg/janet.c are essentially a snapshot (the amalgamated build) of janet at compile time.

janet-pq is from this upstream: https://github.com/andrewchambers/janet-pq/commit/54563c6b675627a2c466615c9600052ea705e94c (which fortunately already seems to have addressed file/popen) - which should make a similar fix in the other project.janet files quite trivial.

The amalg fix should fix itself when I update/test against a new janet.

**Comment by tionis** [comment]
I think this was fixed
